name: Docker Series build

on [push]
jobs: 
  build:
      runs-on: unbuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
           docher build ./c#
           
           
           
        name: Run a multi-line script
        run:
        echo Add other actions to build,
        echo test, and deploy your project.
